### ISSUE TITLE
The tool does not work on QGIS3.4.3

### ISSUE THREAD

**Issue by LoeizT** [JeronimoCarranza/hydronet_check_and_flip-qgis-plugin#1]
Following error message is displayed:

ModuleNotFoundError: No module named 'hydronet_check_and_flip.resources_qrc' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/lth/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\hydronet_check_and_flip\__init__.py", line 34, in classFactory
    from .hydronet_check_and_flip import hydronet_check_and_flip
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/lth/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\hydronet_check_and_flip\hydronet_check_and_flip.py", line 29, in 
    from .resources_qrc import *
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'hydronet_check_and_flip.resources_qrc'

Version de Python : 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Version de QGIS : 3.4.3-Madeira Madeira, 2f64a3c4e7 

Chemin Python :
C:/Users/lth/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks
C:/Users/lth/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour
C:/OSGEO4~1/apps/qgis/./python
C:/Users/lth/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/lth/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:/Users/lth/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\lth\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\cadastre/forms
C:\Users\lth\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:/Users/lth/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2mapillary
C:\Users\lth\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2mapillary\extlibs
C:/Users/lth/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview
C:\Users\lth\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res
C:\Users\lth\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:/Users/lth/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ImportEpanetInpFiles/impcount.py
C:/Users/lth/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\joinmultiplelines
C:\Users\lth\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\lth\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\shapetools\ext-libs
C:/Users/lth/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SwapVectorDirection
C:\Users\lth\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs

**Comment by Jannik-Schilling** [comment]
I found out why:
in the uploaded version in the qgis plugin repository "resources_qrc.py" is missing.

> ModuleNotFoundError: No module named 'hydronet_check_and_flip.resources_qrc'

You can find the file [here ](https://github.com/JeronimoCarranza/hydronet_check_and_flip-qgis-plugin/blob/master/hydronet_check_and_flip/resources_qrc.py) in git.

I downloaded it and added it to my plugin folder manually. Now the plugin is intalled in QGIS 3.4 without any complaints but it still doesn´t work. No buttons or processing tools are loaded.

**Comment by LoeizT** [comment]
Dear Jannick,
Thanks for the feedback.
I tried to copy the hydronet_check_and_flip.resources_qrc file to plugin folder (C:\Users\lth\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\hydronet_check_and_flip) but I still have the same message when trying to activate the plugin. Maybe I didn't place the file at the right location ?

**Comment by Jannik-Schilling** [comment]
No, I used the same folder.
